### PR TITLE
Improve performance by reusing precompiled regular expressions

### PR DESCRIPTION
**Pull request by nazar-pc**
Found this in CPU-bound application, should help significantly when called often.

I am not familiar with the library, would be nice if someone renames variables to something more meaningful.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Found this in CPU-bound application, should help significantly when called often.

Did you actually measure the performance improvement? V8 is often able to inline this anyway, so from experience, whether they are inline or top-level matter very little.

**Comment by sindresorhus** [comment]
You'll also need to come up with some better names for the variables for this to be mergable.

**Comment by nazar-pc** [comment]
> Did you actually measure the performance improvement? V8 is often able to inline this anyway, so from experience, whether they are inline or top-level matter very little.

I do not have a reproducible benchmark. This library is used as dependency of the other library and I found during profiling that a non-negligible amount of time was spent in this library. After changes from this PR I have not seen library doing significant contributions. One would expect something like this to be optimized, but I don't think V8 is doing that right now.

> You'll also need to come up with some better names for the variables for this to be mergable.

I am not familiar with the library at all, so I have no idea what those things do and what they should be called unfortunately.

**Comment by sindresorhus** [comment]
> I am not familiar with the library at all, so I have no idea what those things do and what they should be called unfortunately.

You could infer it by reading the regex and looking at the context.

**Pull request closed without merging**
