### PR TITLE
use var instead of let/const

### PR DESCRIPTION
**Pull request by erossignon**

### CODE REVIEW

**Comment by erossignon** [comment]
this is to fix https://github.com/sindresorhus/camelcase/issues/25

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/camelcase/issues/23

This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by ibc** [comment]
> This module mainly targets Node.js

Don't take me wrong, but how is possible that a JS module that just does stuff on a string "mainly targets Node.js"?

**Comment by ibc** [comment]
Also, where in the doc/README is stated that this module targets Node.js and no the browser?

**Comment by Qix-** [comment]
@ibc It's possible because we're the maintainers and that's how we intend for this to be used. You're more than welcome to transpile for the browser. ES6 is here to stay - you can either adapt, or you can be left behind.

Your choice.

**Comment by ibc** [comment]
I know. BTW I use ES6 with Babel + browserify. 
I understand your point but still consider that a tiny library that performs just string transformations could be, yet, be coded in ES5 so browser app developers don't need to transpile NPM dependencies.

**Pull request closed without merging**
